branch-defaults:
  master:
    environment: paperlastv2-thum-worker
global:
  application_name: paperlastv2-thumbnail-worker
  default_ec2_keyname: Lx001
  default_platform: PHP 5.5
  default_region: sa-east-1
  profile: eb-cli
  sc: git
